### ISSUE TITLE
Use the magiclink token in REST calls

### ISSUE THREAD

**Issue by khashashin** [pyepye/django-magiclink#11]
Is it possible to configure magiclink authenticate backend to allow users call my REST API? Can I send the token that was generated by magiclink in `Autorization` header to authenticate users?

**Comment by pyepye** [comment]
Hi @khashashin 

This plugin was mainly built to work with templates rather than with a front-end making REST calls. Saying that it _MIGHT_ be possible to get it work with some of the customisations available.

The first thing you would need to do is create your own login API view. This would need to take an email address and just call `create_magiclink` then `magiclink.send()` - Info here: https://github.com/pyepye/django-magiclink#creating-magiclinks

Then you would need to look at creating your own [Custom login verify flow](https://github.com/pyepye/django-magiclink#custom-login-verify-flow) which you could use to set any `Autorization` headers or return a response body with a JWT token for example.

Finally I would also see if you can use the `MAGICLINK_LOGIN_FAILED_REDIRECT` setting incase a login fails (https://github.com/pyepye/django-magiclink#configuration-settings). I'm not sure if this setting would work with the front-end being on a different host though.

I hope that helps in some way.


Thanks
Matt

**Comment by khashashin** [comment]
@pyepye  Thank you Matt. In meantime I found another tool that is actually designed to use with DRF is called [djangopasswordless](https://github.com/aaronn/django-rest-framework-passwordless). But with a little effort I think it should be also possible to achieve with django-magiclink
